/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sl_lab2_173212;

import org.junit.Test;
import static org.junit.Assert.*;

public class SILab2Test {

    @Test
    public void test1() {
        User user = new User("dame", "dame", "dame@gmail.com");
        List<User> allUsers = new ArrayList<>();
        boolean result = SILab2.function(user, allUsers);

        assertEquals(true, result);
    }

    @Test
    public void test2() {
        User user = new User("damjan", "dam jan", "dame@gmail.com");
        List<User> allUsers = new ArrayList<>();
        boolean result = SILab2.function(user, allUsers);
        assertEquals(true, result);
    }
}
